# Main Config
version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - js-dependencies-{{ checksum "package.json" }}
      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} >> .npmrc
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: js-dependencies-{{ checksum "package.json" }}

  unit_tests_and_linting:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - js-dependencies-{{ checksum "package.json" }}
          - js-dependencies-
      - run:
          name: Run eslint
          command: npm run eslint -- --format junit -o reports/junit/js-lint-results.xml
      - run:
          name: Run all Jest test suites
          command: npm run jest -- --ci -i --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/jest/js-jest-results.xml
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
          destination: junit

  build_for_tests:
    docker:
      - image: circleci/node:8.11.1
    environment:
      - NODE_ENV: "test"
    steps:
      - checkout
      - restore_cache:
          keys:
          - js-dependencies-{{ checksum "package.json" }}
      - run:
          name: Copy and build journey test static files
          command: npm run build journey /tmp/dist-test
      - persist_to_workspace:
          root: /tmp
          paths:
            - dist-test

  journey_tests:
    docker:
      - image: circleci/node:8.11.1
    environment:
      SAUCE: true
      STATIC_SERVER_PATH: /tmp/workspace/dist-test
    steps:
      - checkout
      - restore_cache:
          keys:
          - js-dependencies-{{ checksum "package.json" }}
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Get JOURNEY_TEST_BASE_URL from Netlify deploy
          command: echo "export JOURNEY_TEST_BASE_URL=$(cat /tmp/workspace/.netlifyUrl)" >> $BASH_ENV
      - run: echo "export BUILD_NUMBER=circle-ci-${CIRCLE_BUILD_NUM}" >> $BASH_ENV
      - run:
          name: Integration Tests
          no_output_timeout: 40m
          command: |
            set -m
            (
              (PORT=4569 SAUCE_CONNECT_PORT=5006 BROWSER=firefox npm run test:integration || kill 0) &
              (sleep 60; PORT=4568 SAUCE_CONNECT_PORT=5005 BROWSER=chrome npm run test:integration || kill 0) &
              (sleep 120; PORT=4567 SAUCE_CONNECT_PORT=5004 BROWSER=chrome PLATFORM="windows 10" npm run test:integration || kill 0) &
              wait
            )
      - store_test_results:
          path: reports/junit/wdio
      - store_artifacts:
          path: reports/junit/wdio
          destination: wdio
      - store_artifacts:
          path: /home/circleci/.npm/_logs/
          destination: npm-logs
      - store_artifacts:
          path: reports/browser
          destination: browser


workflows:
  version: 2
  run_all_tests:
    jobs:
      - install
      - build_for_tests:
          requires:
            - install
      - unit_tests_and_linting:
          requires:
            - install
      - journey_tests:
          requires:
            - build_for_tests
